# docker-compose.yml

services:
  web:
    build: .
    ports:
      - "8000:80" # Map port 80 inside the container to port 8000 on the host
    environment:
      - PORT=80
    env_file:
      - .env

  test:
    build: .
    command: pytest -v
    environment:
      - PORT=80
    env_file:
      - .env
    depends_on:
      - web